import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.Basic
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.SourcePackage
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.SourceDependencies
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.Formalization
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.ReviewerBridge
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.TheoremStatement
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.AdmissibleClass
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.Projection
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.BridgeLemmas
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.GateLemmas
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.FinalTheorem
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.CSemigroupPackage
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.RegularizedSemigroupPackage
import CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean.RegularizationLemma

namespace HautevilleHouse
namespace CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean

theorem root_imports_checked : True := by trivial

end CSemigroupsRegularizedSemigroupsLemmaCanonicalLaneLean
end HautevilleHouse